### ISSUE TITLE
Merging with combat speed.

### ISSUE THREAD

**Issue by Razatop** [Aelto/tw3-resources-perks-overhaul#4]
Want to start off with that I adore your mod and it really makes the game a lot more enjoyable.  

I was wondering how to solve this merge with your mod or if I should just overwrite it. Any insights? 

![image](https://user-images.githubusercontent.com/43615000/129425526-7abf3cda-efde-441b-9874-8a431bd3f62c.png)

**Comment by Aelto** [comment]
Hello ! Glad you enjoy the mod.

In this case, taking C then B should result in a good merge!
